//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMONIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserView
    {
        public Nullable<int> OfficeID { get; set; }
        public string Office { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public string User_Role { get; set; }
        public string LastName { get; set; }
    }
}
